In [1]:
import pandas as pd

In [2]:
genalg_rastrigin_data = pd.read_csv('cust_rastrigin_upd.csv')
genalg_rastrigin_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Растригина,30.0,0.262242,0.487319,0.003097,0.020535,0.096126,0.192999,2.377005
Мода лучшей итерации,30.0,100.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Медиана времени до лучшей итерации,30.0,2.020458,1.031485,0.516509,1.244164,1.736813,2.746589,4.115537
population_size,30.0,309.466667,120.448797,101.000000,233.500000,268.000000,432.000000,488.000000
offspring_ratio,30.0,2.209862,0.434540,1.619716,1.811798,2.268610,2.561825,2.942414
mutation_rate,30.0,0.281287,0.109322,0.116663,0.210593,0.265642,0.354404,0.481803
mutation_strength,30.0,0.302678,0.139458,0.100167,0.160056,0.330871,0.450060,0.497924
mutation_percent_genes,30.0,0.152699,0.026704,0.110887,0.125854,0.157716,0.172184,0.196014
elite_fraction,30.0,0.135685,0.044934,0.051831,0.098078,0.128231,0.176831,0.199961

In [3]:
genalg_shvefel_data = pd.read_csv('cust_shvefel_upd.csv')
genalg_shvefel_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Швефеля,32.0,0.117151,0.217345,0.007330,0.028140,0.048981,0.125291,1.203024
Мода лучшей итерации,32.0,398.656250,7.601398,357.000000,400.000000,400.000000,400.000000,400.000000
Медиана времени до лучшей итерации,32.0,6.418940,2.958408,2.140510,4.434904,5.914803,8.374206,12.964108
population_size,32.0,250.156250,94.990699,100.000000,195.250000,236.000000,309.500000,483.000000
offspring_ratio,32.0,2.372534,0.404771,1.517605,2.106534,2.489706,2.686166,2.973889
mutation_rate,32.0,0.335659,0.125876,0.106020,0.218309,0.347575,0.451863,0.497704
mutation_strength,32.0,0.307530,0.121428,0.109397,0.198282,0.316354,0.415731,0.490349
mutation_percent_genes,32.0,0.145614,0.026316,0.111721,0.122917,0.140097,0.161525,0.197237
elite_fraction,32.0,0.123608,0.041467,0.051635,0.095373,0.121101,0.158165,0.186906

In [4]:
pygad_rastrigin_data = pd.read_csv('pygad_rastrigin.csv')
pygad_rastrigin_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Растригина,30.0,61.270656,96.044538,0.025009,2.713736,21.148338,66.469868,385.131226
Мода лучшей итерации,30.0,59.166667,39.226208,1.000000,19.500000,70.000000,96.750000,100.000000
Медиана времени до лучшей итерации,30.0,9.205164,7.926632,0.073505,3.980530,7.730077,12.243865,32.132207
num_parents_mating,30.0,186.800000,96.248744,20.000000,127.250000,158.500000,239.250000,412.000000
sol_per_pop,30.0,275.133333,127.438351,119.000000,155.250000,245.000000,389.750000,473.000000
num_genes,30.0,19.066667,8.287645,5.000000,12.000000,21.000000,26.750000,30.000000
mutation_percent_genes,30.0,24.293092,15.004136,2.366012,11.536146,24.823780,37.918084,49.280617
random_mutation_min_val,30.0,-4.352784,2.986739,-9.140872,-6.695099,-4.441777,-1.624126,-0.339476
random_mutation_max_val,30.0,4.857614,2.968960,0.421325,2.081585,5.122834,7.197356,9.692230
keep_parents,30.0,0.479301,0.303430,0.031452,0.193796,0.446904,0.788088,0.931668

In [5]:
pygad_shvefel_data = pd.read_csv('pygad_shvefel.csv')
pygad_shvefel_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Швефеля,30.0,339.150882,980.411377,0.004623,0.182056,4.333095,98.254566,4564.869002
Мода лучшей итерации,30.0,50.833333,34.562371,4.000000,18.500000,48.000000,91.250000,100.000000
Медиана времени до лучшей итерации,30.0,30.996559,39.417985,1.090975,6.324268,14.740452,36.734646,169.608371
num_parents_mating,30.0,714.533333,557.298826,102.000000,247.250000,528.500000,1099.250000,1975.000000
sol_per_pop,30.0,1457.833333,795.746064,109.000000,923.000000,1360.500000,2015.750000,2858.000000
mutation_percent_genes,30.0,23.978463,13.316596,1.561154,13.279658,25.149923,31.090669,49.527235
random_mutation_min_val,30.0,-5.655595,2.891383,-9.794854,-8.808101,-5.086888,-3.371041,-0.724696
random_mutation_max_val,30.0,4.982281,3.269902,0.022215,1.865843,4.595692,7.831038,9.650427
keep_parents,30.0,0.437327,0.314965,0.018777,0.120236,0.419638,0.720067,0.962872
num_genes,30.0,18.100000,7.087386,5.000000,14.250000,19.500000,23.000000,30.000000

In [6]:
deap_rastrigin_data = pd.read_csv('deap_rastrigin.csv')
deap_rastrigin_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Растригина,30.0,0.702546,1.949177,0.000000,0.000000,0.000000,0.088347,9.312862
Мода лучшей итерации,30.0,164.066667,204.365280,2.000000,9.500000,38.500000,384.750000,500.000000
Медиана времени до лучшей итерации,30.0,0.011405,0.004340,0.004991,0.007989,0.010987,0.014988,0.019001
Population Size,30.0,295.500000,107.053886,143.000000,200.000000,281.500000,375.250000,482.000000
Mutation Rate,30.0,0.242539,0.136165,0.029704,0.132045,0.231881,0.360423,0.469865
Crossover Rate,30.0,0.285545,0.130777,0.079766,0.174925,0.259588,0.395573,0.499078
Elitism Fraction,30.0,0.108568,0.050241,0.015681,0.085704,0.113298,0.141776,0.181925
Alpha,30.0,0.513628,0.250859,0.036480,0.306686,0.572516,0.694210,0.868970
Mu,30.0,-0.107900,0.604062,-0.961306,-0.596612,-0.137019,0.154684,0.991314
Sigma,30.0,0.455912,0.296519,0.014351,0.212454,0.408885,0.656566,0.997326
Tournament Size,30.0,3.633333,0.964305,2.000000,3.000000,4.000000,4.000000,5.000000

In [7]:
deap_shvefel_data = pd.read_csv('deap_shvefel.csv')
deap_shvefel_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана значения функции Швефеля,30.0,706.477297,750.207250,0.000127,14.774703,452.923203,1234.992272,2385.157349
Мода лучшей итерации,30.0,235.600000,227.342306,1.000000,31.500000,49.500000,499.000000,500.000000
Медиана времени до лучшей итерации,30.0,6.026629,7.661809,0.171506,0.829384,2.130766,7.658966,32.690323
Population Size,30.0,283.766667,114.585816,112.000000,175.250000,274.500000,373.250000,499.000000
Mutation Rate,30.0,0.271129,0.148203,0.013304,0.155089,0.283863,0.398965,0.491548
Crossover Rate,30.0,0.268523,0.149668,0.012321,0.143542,0.298995,0.379139,0.489143
Elitism Fraction,30.0,0.103332,0.056600,0.013096,0.051221,0.102395,0.142387,0.199269
Alpha,30.0,0.470139,0.229145,0.080719,0.275776,0.495142,0.677990,0.808652
Mu,30.0,-0.016602,0.519148,-0.982763,-0.409222,-0.163106,0.485372,0.858289
Sigma,30.0,0.431859,0.272611,0.045287,0.187254,0.424683,0.653305,0.883222
Tournament Size,30.0,3.366667,1.272612,2.000000,2.000000,3.500000,4.750000,5.000000

In [8]:
opt_rastrigin_data = pd.read_csv('opt_rastrigin.csv')
opt_rastrigin_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Значение оптимальной функции,30.0,44.137129,7.226896e-15,44.137129,44.137129,44.137129,44.137129,44.137129
Оптимальная итерация,30.0,483.000000,0.000000e+00,483.000000,483.000000,483.000000,483.000000,483.000000
"Время до оптимальной итерации, сек",30.0,91.602870,7.336829e+00,78.660397,85.824264,90.484160,95.430072,109.991766

In [10]:
opt_shvefel_data = pd.read_csv('opt_shvefel.csv')
opt_shvefel_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Значение оптимальной функции,30.0,683.408493,2.312607e-13,683.408493,683.408493,683.408493,683.408493,683.408493
Оптимальная итерация,30.0,677.000000,0.000000e+00,677.000000,677.000000,677.000000,677.000000,677.000000
"Время до оптимальной итерации, сек",30.0,93.834247,7.630792e+00,76.019600,88.879991,94.692301,98.512070,107.507377

In [11]:
genalg_houses_data = pd.read_csv('cust_houses.csv')
genalg_houses_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Median MSE,29.0,507197.770980,1066.702968,505527.234587,506583.331512,507022.906834,507542.095615,510389.081647
Mode Best Generation,29.0,27.379310,4.427300,17.000000,26.000000,30.000000,30.000000,30.000000
Median Time to Best Generation,29.0,1330.341155,1490.241527,124.057993,639.520506,800.336860,1232.647346,6323.239205
Population Size,29.0,75.206897,91.757981,19.000000,33.000000,46.000000,54.000000,431.000000
Mutation Rate,29.0,0.321960,0.107439,0.133698,0.238423,0.325108,0.413523,0.480294
Offspring Ratio,29.0,2.279213,0.430640,1.506280,1.926728,2.227904,2.607310,2.995325
Mutation Strength,29.0,0.272582,0.105225,0.108048,0.199472,0.270665,0.382512,0.443792
Mutation Percent Genes,29.0,0.153147,0.028249,0.106731,0.128875,0.150517,0.177809,0.196286
Elite Fraction,29.0,0.132252,0.043047,0.061322,0.097204,0.143702,0.169497,0.195376

In [12]:
deap_houses_data = pd.read_csv('deap_houses.csv')
deap_houses_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана MSE,29.0,506131.877901,1630.478855,501951.551700,505057.391616,506442.556737,507539.916359,508384.076171
Мода лучшей итерации,29.0,9.000000,7.348469,1.000000,1.000000,8.000000,15.000000,20.000000
Медиана времени до лучшей итерации,29.0,143.291704,111.365230,11.589091,60.655390,128.330109,193.347261,523.782465
Population Size,29.0,277.137931,134.387692,48.000000,164.000000,264.000000,406.000000,499.000000
Mutation Rate,29.0,0.262564,0.140500,0.021105,0.174169,0.262477,0.373044,0.488323
Crossover Rate,29.0,0.283615,0.143545,0.034707,0.194515,0.278539,0.433540,0.485427
Elitism Fraction,29.0,0.091816,0.056897,0.012051,0.039495,0.075488,0.152723,0.189328
Alpha,29.0,0.487912,0.219818,0.094137,0.319568,0.517456,0.612120,0.897401
Mu,29.0,0.007949,0.687843,-0.981995,-0.545262,-0.075521,0.692470,0.986211
Sigma,29.0,0.491450,0.307555,0.029168,0.251739,0.384297,0.782772,0.953445
Tournament Size,29.0,3.551724,1.212618,2.000000,3.000000,3.000000,5.000000,5.000000

In [13]:
pygad_houses_data = pd.read_csv('pygad_houses.csv')
pygad_houses_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Медиана MSE,30.0,508689.000813,3607.180582,503582.667955,506974.483128,507916.289583,508862.054337,520790.613027
Мода лучшей итерации,30.0,20.000000,0.000000,20.000000,20.000000,20.000000,20.000000,20.000000
Медиана времени до лучшей итерации,30.0,292.892840,244.431831,21.394141,124.957117,225.423688,385.331217,853.007792
num_parents_mating,30.0,7.366667,2.326509,2.000000,6.000000,8.000000,9.000000,10.000000
sol_per_pop,30.0,52.266667,29.411390,10.000000,23.750000,50.500000,80.250000,98.000000
mutation_percent_genes,30.0,25.093171,13.853448,1.472902,14.168593,25.482135,38.010440,48.105758
mutation_num_genes,30.0,2.066667,0.907187,1.000000,1.000000,2.000000,3.000000,3.000000
random_mutation_min_val,30.0,-0.048282,0.027623,-0.099883,-0.068788,-0.045151,-0.026720,-0.005014
random_mutation_max_val,30.0,0.052511,0.031266,0.004486,0.024749,0.058267,0.080620,0.099262
num_genes,30.0,6.000000,0.000000,6.000000,6.000000,6.000000,6.000000,6.000000

In [14]:
optuna_houses_data = pd.read_csv('opt_houses.csv')
optuna_houses_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Лучшее значение MSE,1.0,501628.548547,NaN,501628.548547,501628.548547,501628.548547,501628.548547,501628.548547
Лучшая итерация,1.0,231.000000,NaN,231.000000,231.000000,231.000000,231.000000,231.000000
Время до лучшей итерации (секунды),1.0,202.900064,NaN,202.900064,202.900064,202.900064,202.900064,202.900064